import os
import time
import json

# Set Protocol Buffers implementation before importing libraries
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

import streamlit as st
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import List, Optional, TypedDict
import chromadb
from chromadb.utils import embedding_functions

from langchain_groq import ChatGroq
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import StateGraph, START, END

# ==============================================================================
# 1. ENVIRONMENT & CONFIGURATION SETUP
# ==============================================================================
# Load environment variables from .env file (e.g., GROQ_API_KEY)
load_dotenv()
api_key = os.getenv("GROQ_API_KEY")

# ==============================================================================
# 2. PYDANTIC SCHEMAS DEFINITION
# ==============================================================================
# These Pydantic models define the exact structured JSON formats expected 
# from the AI agent responses.

class InvoiceItem(BaseModel):
    """Represents an individual line item inside an invoice."""
    description: str = Field(description="Description of goods or services")
    quantity: int = Field(description="Quantity purchased")
    unit_price: float = Field(description="Unit price per item")
    line_total: float = Field(description="Total line item price")

class InvoiceSchema(BaseModel):
    """Represents structured invoice data extracted from raw text by Agent 1."""
    vendor_name: str = Field(description="Name of vendor")
    po_number: Optional[str] = Field(None, description="PO number")
    invoice_date: str = Field(description="Issue date")
    invoice_total: float = Field(description="Final total amount")
    has_tax_id: bool = Field(description="True if Tax ID is present")
    payment_terms: str = Field(default="Net-30", description="Payment terms")
    line_items: List[InvoiceItem] = Field(default_factory=list, description="Item list")

class AuditResult(BaseModel):
    """Represents policy compliance audit results evaluated by Agent 2."""
    is_compliant: bool = Field(description="True if compliant")
    flagged_violations: List[str] = Field(default_factory=list, description="Policy violations")
    risk_score: str = Field(description="LOW, MEDIUM, or HIGH risk")

class ActionPayload(BaseModel):
    """Represents operational recommendations and drafted outputs generated by Agent 3."""
    recommended_action: str = Field(description="AUTO_APPROVE, FLAG_FOR_REVIEW, REJECT")
    email_draft: str = Field(description="Drafted response email")
    ticket_summary: str = Field(description="Ticket summary")

# ==============================================================================
# 3. PARSERS & VECTOR STORE (RAG) SETUP
# ==============================================================================
# Output parsers enforce strict JSON structure alignment with our Pydantic models
extraction_parser = PydanticOutputParser(pydantic_object=InvoiceSchema)
audit_parser = PydanticOutputParser(pydantic_object=AuditResult)
action_parser = PydanticOutputParser(pydantic_object=ActionPayload)

class PolicyVectorStore:
    """Manages procurement policy search queries against ChromaDB vector embeddings."""
    def __init__(self, persistence_dir: str = "./chroma_db"):
        # Connect to persistent ChromaDB vector store directory
        self.chroma_client = chromadb.PersistentClient(path=persistence_dir)
        # Load local text embedding model
        self.emb_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"
        )
        # Access or create the policy collection
        self.collection = self.chroma_client.get_or_create_collection(
            name="procurement_policies",
            embedding_function=self.emb_fn
        )

    def query_policy(self, query_text: str, n_results: int = 2) -> list[str]:
        """Queries vector database to find matching procurement policy chunks."""
        results = self.collection.query(
            query_texts=[query_text],
            n_results=n_results
        )
        return results["documents"][0] if results["documents"] else []

# ==============================================================================
# 4. LLM & VECTOR STORE INITIALIZATION
# ==============================================================================
selected_model = "openai/gpt-oss-20b"
llm = ChatGroq(
    model_name=selected_model,
    groq_api_key=api_key,
    temperature=0.0
)
vector_store = PolicyVectorStore()

# ==============================================================================
# 5. PIPELINE STATE & AGENT NODES
# ==============================================================================
class CopilotState(TypedDict):
    """Defines shared state object passed across nodes in the LangGraph workflow."""
    raw_invoice_text: str
    po_limit: float
    extracted_invoice: InvoiceSchema
    audit_report: AuditResult
    final_action: ActionPayload

def extraction_agent(state: CopilotState) -> dict:
    """AGENT 1: Converts unstructured raw invoice text into structured JSON schema."""
    prompt = f"""
You are a precision data extraction system. Extract billing details from raw invoice text below.

{extraction_parser.get_format_instructions()}

Invoice Text:
{state['raw_invoice_text']}
"""
    raw_response = llm.invoke(prompt)
    extracted_data = extraction_parser.parse(raw_response.content)
    return {"extracted_invoice": extracted_data}

def policy_audit_agent(state: CopilotState) -> dict:
    """AGENT 2: Audits extracted invoice details against RAG procurement policies."""
    inv = state["extracted_invoice"]
    po_limit = state.get("po_limit", inv.invoice_total)

    # Perform RAG retrieval against ChromaDB for relevant rules
    retrieved_policies = vector_store.query_policy(
        f"Invoice total {inv.invoice_total} vs PO limit {po_limit}, tax ID rules, payment terms {inv.payment_terms}"
    )
    context_str = "\n---\n".join(retrieved_policies)

    prompt = f"""
You are an automated procurement compliance auditor. Compare invoice details against policy rules.

{audit_parser.get_format_instructions()}

Relevant Procurement Policies:
{context_str}

Extracted Invoice Details:
- Vendor: {inv.vendor_name}
- Invoice Total: ${inv.invoice_total:.2f}
- PO Expected Limit: ${po_limit:.2f}
- Tax ID Present: {inv.has_tax_id}
- Payment Terms: {inv.payment_terms}

Determine compliance, highlight rule violations, and assign a risk level.
"""
    raw_response = llm.invoke(prompt)
    audit_res = audit_parser.parse(raw_response.content)
    return {"audit_report": audit_res}

def action_agent(state: CopilotState) -> dict:
    """AGENT 3: Generates final operator payload, email draft, and ticket summary."""
    inv = state["extracted_invoice"]
    audit = state["audit_report"]

    prompt = f"""
You are a procurement resolution officer. Generate an operational action payload and vendor response email.

{action_parser.get_format_instructions()}

Invoice Summary:
- Vendor: {inv.vendor_name}
- Total: ${inv.invoice_total:.2f}
    
Audit Report:
- Compliant: {audit.is_compliant}
- Risk Level: {audit.risk_score}
- Violations: {', '.join(audit.flagged_violations) if audit.flagged_violations else 'None'}

Instructions:
1. Set recommended_action to AUTO_APPROVE if compliant, else FLAG_FOR_REVIEW.
2. Draft a clear, polite professional resolution email addressing discrepancies.
3. Provide a concise single-sentence internal ticket summary.
"""
    raw_response = llm.invoke(prompt)
    action_res = action_parser.parse(raw_response.content)
    return {"final_action": action_res}

# ==============================================================================
# 6. LANGGRAPH WORKFLOW COMPILATION
# ==============================================================================
# Define multi-agent workflow graph execution flow
workflow = StateGraph(CopilotState)
workflow.add_node("ExtractionAgent", extraction_agent)
workflow.add_node("PolicyAuditAgent", policy_audit_agent)
workflow.add_node("ActionAgent", action_agent)

# Set execution order: Start -> Agent 1 -> Agent 2 -> Agent 3 -> End
workflow.add_edge(START, "ExtractionAgent")
workflow.add_edge("ExtractionAgent", "PolicyAuditAgent")
workflow.add_edge("PolicyAuditAgent", "ActionAgent")
workflow.add_edge("ActionAgent", END)

copilot_app = workflow.compile()

# ==============================================================================
# 7. STREAMLIT USER INTERFACE (UI)
# ==============================================================================
st.set_page_config(page_title="Procurement Exception Copilot", page_icon="🤖", layout="wide")

st.title("🤖 Multi-Agent Procurement Exception Copilot")
st.caption("Automated Invoice Extraction, RAG Policy Audit & Human-in-the-Loop Review")

# Sidebar Execution Controls
st.sidebar.header("Execution Controls")
po_limit_input = st.sidebar.number_input("Expected PO Limit ($)", value=2000.0, step=100.0)

# Default invoice text fallback
sample_invoice_default = """INVOICE #INV-9082
Vendor: Apex Tech Solutions
Date: 2026-03-12
PO Number: PO-8831

Items Purchased:
1. Enterprise Cloud Subscription (Qty: 1) - $2,250.00
Tax ID / GSTIN: Not Provided
Payment Terms: Immediate

Total Amount Due: $2,250.00"""

# ------------------------------------------------------------------------------
# DYNAMIC CASE SELECTION DROPDOWN (LOADS FROM JSON)
# ------------------------------------------------------------------------------
cases_dict = {}
json_path = "procurement_cases.json"

# Check if data/procurement_cases.json exists and load cases dynamically
if os.path.exists(json_path):
    try:
        with open(json_path, "r") as f:
            cases_list = json.load(f)
            for idx, case in enumerate(cases_list):
                vendor = case.get("vendor_name") or case.get("vendor") or case.get("supplier") or f"Vendor {idx+1}"
                po = case.get("po_number") or case.get("po_reference") or case.get("po") or "No PO"
                case_title = f"Case {idx + 1}: {vendor} ({po})"
                
                # Extract text content
                text_content = case.get("raw_invoice_text") or case.get("raw_text", str(case))
                cases_dict[case_title] = text_content
    except Exception as e:
        st.warning(f"Could not load procurement cases JSON: {e}")

# Render Dropdown Selectbox if JSON cases exist, else fallback to default text
if cases_dict:
    selected_case_title = st.selectbox(
        "📋 Select Sample Invoice Case from Database:", 
        options=list(cases_dict.keys())
    )
    initial_text = cases_dict[selected_case_title]
else:
    initial_text = sample_invoice_default

# Text area pre-populated with selected invoice text
raw_text = st.text_area("Raw Invoice / Vendor Email Input", value=initial_text, height=220)

# ------------------------------------------------------------------------------
# AUDIT EXECUTION BUTTON AND RESULTS DISPLAY
# ------------------------------------------------------------------------------
if st.button("Run Multi-Agent Audit", type="primary"):
    start_time = time.perf_counter()
    
    with st.spinner("Agents processing (Extraction -> Audit -> Action)..."):
        inputs = {
            "raw_invoice_text": raw_text,
            "po_limit": float(po_limit_input)
        }
        result = copilot_app.invoke(inputs)
    
    elapsed_time = time.perf_counter() - start_time
    st.success(f"Multi-Agent Pipeline executed in {elapsed_time:.2f} seconds!")

    col1, col2 = st.columns(2)

    # Column 1: Extraction & Audit Results
    with col1:
        st.subheader("1. Extracted Invoice Details")
        inv = result["extracted_invoice"]
        st.json(inv.model_dump())

        st.subheader("2. Compliance Audit Findings")
        audit = result["audit_report"]
        if audit.is_compliant:
            st.success(f"Status: COMPLIANT | Risk Level: {audit.risk_score}")
        else:
            st.error(f"Status: NON-COMPLIANT | Risk Level: {audit.risk_score}")
            st.write("**Violations Flagged:**")
            for v in audit.flagged_violations:
                st.write(f"- {v}")

    # Column 2: Human-in-the-Loop Operator Actions
    with col2:
        st.subheader("3. Human-in-the-Loop Operator Review")
        action = result["final_action"]
        
        st.selectbox("Recommended Action", ["AUTO_APPROVE", "FLAG_FOR_REVIEW", "REJECT"], 
                     index=0 if action.recommended_action == "AUTO_APPROVE" else 1)
        
        st.text_input("Internal Ticket Summary", value=action.ticket_summary)
        
        edited_email = st.text_area("Resolution Email Draft (Editable)", value=action.email_draft, height=220)
        
        b1, b2 = st.columns(2)
        if b1.button("Approve & Send Email"):
            st.balloons()
            st.success("Action logged & resolution email dispatched!")
        if b2.button("Override / Reject Ticket"):
            st.warning("Ticket rejected & escalated to manual queue.")
